name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run the job and capture logs
      run: |
        echo "Running the job"
        echo "Example log line" > logs.txt
        # Run your build/test commands and append logs to logs.txt
        # For example: npm install && npm test >> logs.txt 2>&1

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs.txt

    
